var lang = {
	'remove_friends' 		: "Quitar de mis amigos",
	'see_last_postyle' 		: "Ver ultimo postyle",
	'add_friends' 			: "Agregar a mis amigos",
	'like' 					: "Me gusta",
	'unlike' 				: "No me gusta",
	'comment' 				: "Comentar",
	'rankear' 				: "Rankear",
	'first' 				: "Primera",
	'last' 					: "Ultima",
	'see_all'				: "Ver Todos",
	'details'				: "Detalles",
	'used_in'				: "Usado en",
	'purchased_in'			: "Comprado en",
	'sub_categorys'			: "Subcategorias",
	'deletee'				: "Eliminar",
	'add_comment'			: "Agregar comentario",
	'brand'					: "Marca",
	'price'					: "Precio",
	'purchased_in'			: "Comprado en",
	'recommendations'		: "Recomendaciones",
	'my'					: "Mis",
	'wall'					: "Muro",
	'friends'				: "Amigos",
	'awards'				: "Premios",
	'whats_your_style'		: "¿Cuál es tu estilo?",
	'create_postyle'		: "Crear Postyle",
	'ocation'				: "Ocasión",
	'date'					: "Fecha",
	'view_more'				: "Ver Más",
	'new_postyle'			: "Nuevo Postyle",
	'upload_photo'			: "Sube la foto",
	'upload'				: "Subir",
	'publish'				: "Publicar",
	'email'					: "Email",
	'man'					: "Hombre",
	'women'					: "Mujer",
	'name'					: "Nombre",
	'sexo'					: "Sexo",
	'more_detaild'			: "Más Detalles",
	'add'					: "Agregar",
	'hide_details'			: "Ocultar Detalles",
	'store'					: "Tienda",
	'title'					: "Título",
	'features'				: "Características",
	'phones'				: "Teléfonos",
	'websites'				: "Web",
	'address'				: "Dirección",
	'products'				: "Productos",
	'description'			: "Descripción",
	'located_in'			: "Ubicado en",
	'view_map'				: "Ver Mapa",
	'cancel_invitation'		: "Cancelar invitación"
};